apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  namespace: a2billing
spec:
  ports:
  - nodePort: 30337
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin
  type: NodePort
