apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-admin
  name: web-admin
  namespace: a2billing
spec:
  ports:
  - nodePort: 30335
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-admin
  type: NodePort
