apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-customer
  name: web-customer
  namespace: a2billing
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-customer
  type: ClusterIP
