apiVersion: v1
kind: Service
metadata:
  labels:
    app: sip-server
  name: sip-server
  namespace: a2billing
spec:
  ports:
  - nodePort: 30336
    name: tcp
    port: 5060
    protocol: TCP
    targetPort: 5060
  - nodePort: 30336
    name: udp
    port: 5060
    protocol: UDP
    targetPort: 5060
  selector:
    app: sip-server
  type: NodePort
